version: '3.8'

services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=postgres_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=stydjbSDF23dsajfiO
      - POSTGRES_DB=auth
      - SECRET_KEY=34912@445dfsdFBSD23reg@F587
      - ACCESS_TOKEN_EXPIRE_MINUTES=15
    networks:
      - app-network
    env_file:
      - .env

  db:
    image: postgres:latest
    container_name: postgres_db
    networks:
      - app-network
    restart: always
    command: ["postgres", "-c", "fsync=off"]
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=stydjbSDF23dsajfiO
      - POSTGRES_DB=auth

networks:
  app-network:
    driver: bridge
