version: '3.8'

services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=postgres_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=stydjbSDF23dsajfiO
      - POSTGRES_DB=auth
      - SECRET_KEY=34912@445dfsdFBSD23reg@F587
      - ACCESS_TOKEN_EXPIRE_MINUTES=15
    networks:
      - app-network

  db:
    image: postgres:latest
    container_name: postgres_db
    networks:
      - app-network
    restart: always
    command: ["postgres", "-c", "fsync=off"]
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=stydjbSDF23dsajfiO
      - POSTGRES_DB=auth
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge
